

body_fit = {'Maternity': set(['Tops', 'Jeans Trousers', 'Accessories', 'Footwear']), 
            'Curve and plus size': set(['Dresses', 'Tops','Accessories', 'Skirts', 'Footwear']),
            'Petite': set(['Dresses', 'Tops','Accessories', 'Footwear']), 
            'Tall': set(['Skirts', 'Jeans Trousers','Accessories', 'Tops','Footwear']), 
            'Hourglass': set(['Jeans Trousers', 'Tops', 'Accessories', 'Footwear'])}

cloth_categories = {'Bags': set({'Backpacks': [{'Design': 'ASOS DESIGN soft backpack with zip', 'Color': 'Black', 'Price': 'USD 38.00'}, 
                                               {'Design': 'BASIC PLEASURE drawstring backpack', 'Color': 'Khaki', 'Price': 'USD 42.64'}], 
                                 'Bum Bags': [{'Design': 'POLO RALPH LAUREN bum bag with pony logo', 'Color': 'Yellow', 'Price': 'USD 119.00'}, 
                                               {'Design': 'CHAMPION bum bag', 'Color': 'Beige', 'Price': 'USD 23.00'}], 
                                 'Wallets': [{'Design': 'LOVE MOSCHINO quilted wallet', 'Color': 'Purple', 'Price': 'USD 48.70'}, 
                                               {'Design': 'ARMANI EA7 logo zip around wallet', 'Color': 'White', 'Price': 'USD 76.04'}], 
                                 'Clutch bags': [{'Design': 'ASOS DESIGN tassel clutch bag', 'Color': 'Sage', 'Price': 'USD 36.32'}, 
                                               {'Design': 'ALDO beaded miniball grab bag', 'Color': 'Gold', 'Price': 'USD 37.00'}], 
                                 'Sling bags': [{'Design': 'ARTSAC Jaspar triple pocket cross body bag', 'Color': 'Stone', 'Price': 'USD 47.37'}, 
                                               {'Design': 'TOMMY HILFIGER jeans flag logo sling bag', 'Color': 'Cream', 'Price': 'USD 190.00'}]}),
            'Dresses': set({'Wrap dresses': [{'Design': 'ASOS DESIGN wrap balloon sleeve midi dress', 'Color': 'Black', 'Price': 'USD 32.06'}, 
                                               {'Design': 'GEORGIA LOUISE satin ruffle hem', 'Color': 'Pink', 'Price': 'USD 31.58'}],
                            'Trapeze dresses': [{'Design': 'ASOS DESIGN tall highneck pleated trapeze mini dress', 'Color': 'Mint', 'Price': 'USD 26.84'}, 
                                               {'Design': 'WHISTLES mini trapeze dress in green floral', 'Color': 'Floral', 'Price': 'USD 192.64'}],
                            'Bandeau dresses': [{'Design': 'ARIA COVE bandeau plunge wire maxi dress', 'Color': 'Aqua', 'Price': 'USD 21.32'}, 
                                               {'Design': 'LACE and BEADS tulle bandeau mini dress', 'Color': 'Mangenta', 'Price': 'USD 133.00'}],
                            'Fish tail dresses': [{'Design': 'GODDOVA BARDOT fishtail maxi dress', 'Color': 'Powder Blue', 'Price': 'USD 41.85'}, 
                                               {'Design': 'MAYA BRIDAL embellished fishtail maxi dress', 'Color': 'Ivory', 'Price': 'USD 266.00'}],
                            'Jumper dresses': [{'Design': 'THREADBARE Petite Parker off shoulder', 'Color': 'Taupe', 'Price': 'USD 22.90'}, 
                                               {'Design': 'WEDNESDAYS GIRL chunky rib zip through funnel dress ', 'Color': 'Ivory', 'Price': 'USD 26.84'}]}),
            'Footwear': set({'Sneakers': [{'Design': 'NEW BALANCE 610 trainers', 'Color': 'Green', 'Price': 'USD 174.00'}, 
                                               {'Design': 'ADIDAS Originals', 'Color': 'Cream and Black', 'Price': 'USD 143.00'}],
                             'Sandals': [{'Design': 'TOP SHOP Rosie ankle tie strippy sandal', 'Color': 'Blue', 'Price': 'USD 20.83'}, 
                                               {'Design': 'PUBLIC DESIRE Wide Fit platform sandals', 'Color': 'Pink', 'Price': 'USD 19.64'}],
                             'Heels': [{'Design': 'BEBO Mariya bridal pearl high heeled clear shoe', 'Color': 'White', 'Price': 'USD 21.32'}, 
                                               {'Design': 'ASOS DESIGN Nation stiletto heels', 'Color': 'Brown', 'Price': 'USD 28.42'}],
                             'Chelsea Boots': [{'Design': 'ASOS DESIGN Anthem chunky chelsea boots', 'Color': 'Off-white', 'Price': 'USD 22.42'}, 
                                               {'Design': 'TRUFFLE COLLECTION chelsea boots with gold trim', 'Color': 'Black Croc', 'Price': 'USD 48.00'}],
                             'Loafers': [{'Design': 'DAISY STREET Exclusive double heeled loafers', 'Color': 'Lavender', 'Price': 'USD 25.24'}, 
                                               {'Design': 'RIVER ISLAND chunky snaffle loafer', 'Color': 'Red', 'Price': 'USD 61.00'}]}),
            'Accessories': set({'Neck pieces': [{'Design': 'DESIGN B London layered pearl neck lace', 'Color': 'Off-white', 'Price': 'USD 17.00'}, 
                                               {'Design': 'ASOS DESIGN chocker necklace with wide crystals', 'Color': 'Silver', 'Price': 'USD 31.00'}],
                                'Scarves': [{'Design': 'RECLAIMED Vintage sequin scarf', 'Color': 'Silver', 'Price': 'USD 18.16'}, 
                                               {'Design': 'MY ACCESSORIES shimmer lighweight scarf', 'Color': 'Brown', 'Price': 'USD 16.00'}],
                                'Finger Rings': [{'Design': 'ASOS DESIGN stacked ring with molten design', 'Color': 'Black', 'Price': 'USD 12.42'}, 
                                               {'Design': 'WHISTLES statement buckle ring', 'Color': 'Gold', 'Price': 'USD 10.50'}],
                                'Earrings': [{'Design': 'ASOS DESIGN stud earrings with long drop design', 'Color': 'Red', 'Price': 'USD 13.52'}, 
                                               {'Design': 'DESIGN B London oversized stud earrings', 'Color': 'Mint', 'Price': 'USD 20.00'}],
                                'Anklets': [{'Design': 'ASOS DESIGN anklet with faux pearl and crytal cupchain', 'Color': 'Green', 'Price': 'USD 26.90'}, 
                                               {'Design': 'ALDO single anklet with hanging balls', 'Color': 'Gold', 'Price': 'USD 48.00'}]}),
            'Tops': set({'Polo-shirts': [{'Design': 'ADIDAS Originals 70s stripe polo shirt', 'Color': 'Dark Green', 'Price': 'USD 44.20'}, 
                                               {'Design': 'PINKIE Wrap front polo oversized long sleeve', 'Color': 'Blue', 'Price': 'USD 17.37'}],
                         'Crop Tops': [{'Design': 'TRUE NORTH Face cropped tank top', 'Color': 'White', 'Price': 'USD 34.74'}, 
                                               {'Design': 'ONLY Executive halter neck top', 'Color': 'Purple', 'Price': 'USD 16.58'}],
                         'Corset Tops': [{'Design': 'LOLA MAY Tall Satin corset crop top', 'Color': 'Brown', 'Price': 'USD 9.47'}, 
                                               {'Design': 'ASOS DESIGN bandeau corset with hook and eye', 'Color': 'Berry', 'Price': 'USD 24.48'}],
                         'Kimonos': [{'Design': 'BRAVE SOUL Plus Maxi beach kimono', 'Color': 'Green and Pink', 'Price': 'USD 23.69'}, 
                                               {'Design': 'ASOS DESIGN Maxi beach kimono', 'Color': 'Magenta', 'Price': 'USD 31.00'}],
                         'Bodies': [{'Design': 'UNIQUE 21 Petite plunge tailored bodysuit', 'Color': 'Pink', 'Price': 'USD 21.32'}, 
                                               {'Design': 'STRADIVARIUS Off Shoulder bodysuit with twist bust', 'Color': 'Black', 'Price': 'USD 7.90'}]}),
            'Jeans Trousers': set({'Skinny jeans': [{'Design': 'DTT Chloe disco stretch skinny jeans', 'Color': 'Mid wash blue', 'Price': 'USD 15.79'}, 
                                               {'Design': 'STRADIVARIUS Tall super skinny jeans', 'Color': 'Grey', 'Price': 'USD 11.05'}],
                                   'High Waisted jeans': [{'Design': 'PULL & BEAR High waisted jeans', 'Color': 'Medium Blue', 'Price': 'USD 22.90'}, 
                                               {'Design': 'ASOS DESIGN Hourglass high waisted jeans', 'Color': 'Berry', 'Price': 'USD 45.37'}],
                                   'Shorts': [{'Design': 'NOISY MAY Tall Frayed hem longline denim', 'Color': 'Black', 'Price': 'USD 17.20'}, 
                                               {'Design': 'DTT Petite skinny denim shorts', 'Color': 'Grey', 'Price': 'USD 12.63'}],
                                   'Flared jeans': [{'Design': 'ASOS DESIGN kickflare jeans in pinstripe', 'Color': 'Grey', 'Price': 'USD 28.42'}, 
                                               {'Design': 'URBAN REVIVO flare jeans', 'Color': 'Blue', 'Price': 'USD 53.00'}],
                                   'Ripped jeans': [{'Design': 'PARISIAN Tall Skinny jeans with rips', 'Color': 'Mid wash blue', 'Price': 'USD 22.11'}, 
                                               {'Design': 'STRADIVARIUS jeans with ripped knee', 'Color': 'Green', 'Price': 'USD 26.84'}]}),
            'Skirts': set({'Pleated skirts': [{'Design': 'ASOS DESIGN pleated midi skirt', 'Color': 'Baby Pink', 'Price': 'USD 27.63'}, 
                                               {'Design': 'COLLUSION box pletaed midi skirt with high split', 'Color': 'Berry', 'Price': 'USD 11.05'}],
                           'A line skirts': [{'Design': 'MISS SELFRIDGE chiffon lace gadet maxi skirt', 'Color': 'Floral', 'Price': 'USD 23.79'}, 
                                               {'Design': 'BAUUUT Tall Tulle maxi skirt', 'Color': 'Lavender', 'Price': 'USD 26.06'}],
                           'Bodycon skirts': [{'Design': 'PUBLIC DESIRE faux leather co-ord skirt', 'Color': 'Red', 'Price': 'USD 30.79'}, 
                                               {'Design': 'FIRE AND GLORY Christine ruched midi skirt', 'Color': 'Brown', 'Price': 'USD 11.05'}],
                           'Mini skirts': [{'Design': 'MISS EMPIRE knitted mini skirt co-ord', 'Color': 'Cream', 'Price': 'USD 27.00'}, 
                                               {'Design': 'JDY Frill detail mini skirt in red and pink floral', 'Color': 'Red and Pink', 'Price': 'USD 17.37'}],
                           'Jipsy skirts': [{'Design': 'LIPSY Jipsy skirt in floral print', 'Color': 'Floral', 'Price': 'USD 31.58'}, 
                                               {'Design': 'STRADIVARIUS Midi Jipsy skirt in Fuschia', 'Color': 'Fuschia', 'Price': 'USD 37.98'}]})}



